mybatis:
  mapper-locations: classpath:mappers/*Mapper.xml
  type-aliases-package: com.wgymt.entity
spring:
  datasource:
    druid:
      url: jdbc:mysql://192.168.123.219:3306/fmmall?characterEncoding=utf8&useSSL=false
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: 123456
server:
  port: 8888
